server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/perfume_shop?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Email config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lucy139200556@gmail.com
spring.mail.password=wlzsaayaahqogdbs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# VNPay config
vnpay.tmnCode=CGXZURGQ
vnpay.hashSecret=REAZ2ZDFDVEOPVNZJGKCFRNZEUXIMXPN
vnpay.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=http://localhost:8081/payment/vnpay-return
vnpay.apiUrl=https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
