# Cấu hình cổng chạy Server Spring Boot (không liên quan đến cổng Apache của Laragon)
server.port=8081

# Cấu hình kết nối đến MySQL của Laragon
spring.datasource.url=jdbc:mysql://localhost:3306/perfume_shop?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=

# Hibernate tự động cập nhật bảng vào Laragon Database
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Tắt cache Thymeleaf để tự động reload template khi thay đổi (dùng khi phát triển)
spring.thymeleaf.cache=false

# Cấu hình upload file ảnh (tối đa 5MB)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# ===============================
# CẤU HÌNH GỬI EMAIL (GMAIL SMTP)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=lucy139200556@gmail.com
spring.mail.password=wlzsaayaahqogdbs

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# CẤU HÌNH VNPAY SANDBOX
# ===============================
# Thông tin tài khoản sandbox VNPay (đã được cập nhật theo tài khoản của bạn)
vnpay.tmnCode=N77AE6DX
vnpay.hashSecret=7UQABRLAUWSU0AVSZ71RVHOF2QJ9QM42
vnpay.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=http://localhost:8081/payment/vnpay-return
vnpay.apiUrl=https://sandbox.vnpayment.vn/merchant_webapi/api/transaction